language: node_js
node_js:
  - "10.4.0"
branches:
  only:
    - master
script:
  - npm install
  - ng build --prod
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN